### ISSUE TITLE
Weather widget is not working outside of China

### ISSUE THREAD

**Issue by azagor** [ERap320/LenovoWatchMOD#18]
It seems that availability of that widget is just blocked by checking if user location is in China. It seems to be done in a quite primitive way:
1.First it checks if map data is available. If not Widget won't be available in the watch and app:
![92297517_556933888260688_196644618085859328_n](https://user-images.githubusercontent.com/10886050/78584222-2ad00900-7838-11ea-92df-be63aad35add.png)
2. That function is just checking it by comparing latitude and longitude:
here:
![92099910_211106320172150_5480902191281602560_n](https://user-images.githubusercontent.com/10886050/78584493-91552700-7838-11ea-8371-50af453c566f.png)
and then this:
![92099654_1667196313434502_590503452820373504_n](https://user-images.githubusercontent.com/10886050/78584587-b5b10380-7838-11ea-84e8-c54fc06b83fc.png)

Maybe it would be possible to remove that check entirely.

**Comment by ERap320** [comment]
I will sure be easier now that you found the culprit. I'll try as soon as I can.

**Comment by azagor** [comment]
@ERap320 I wanted to try build apk myself but I failed :( ( probably the way I unpacked apk is wrong ) I've never used android studio before. I have a bit more time then usual right now so I maybe I will learn. Anyway don't hesitate to ask me for some help on this. I will try my best.

**Comment by ERap320** [comment]
@azagor As you seem very collaborative and good willed I would kindly ask you to try the APK from the [maps-check branch](https://github.com/ERap320/LenovoWatchMOD/tree/maps-check), where I made the _isAMapDataAvailable_ function always return true, in both its definitions.
I made no release for this but I'm sure if you managed to decompile the APK you also know how to download the file ;)
I'd gladly test it myself but, as I said in other discussions, I only have a Watch 9 and no Watch X.

The question now is if the lock was in place because the service they use only has data for China. In that case there is not much else to do.

**Comment by azagor** [comment]
hey, thank you for working on this. I downloaded apk. Weather widget did
not appear. Probably it is disabled in yet some other place asewll.
Although there are some other unexpected  results of that change.
1. After login in to lenovo account I can see heart rate, mood and sleep
data on the main panel.
2. When I enter for example heart rate widget I no longer get the error
message from the server, but I also don't see any data there. It seems that
they have data syncing with the server also tide user location

wt., 7 kwi 2020 o 10:16 ERap320 <notifications@github.com> napisał(a):

**Comment by azagor** [comment]
no. I am sorry! The data appeared. It just took some time, You fixed data
syncing! Man those bastard limited this to China on official app. Thank
you!

wt., 7 kwi 2020 o 10:50 Łukasz Szczepankowski <szczepankowski@gmail.com>
napisał(a):

**Comment by ERap320** [comment]
> 
> no. I am sorry! The data appeared. It just took some time, You fixed data syncing! Man those bastard limited this to China on official app. Thank you!

Looks like we're pretty lucky! lol
Thank you very much for your reverse engineering, that saved a lot of time.

If you're ok with that I would also close the other issue since it seems we solved it as well. I'll reference this one while closing it for clarity.
If you need anything else, don't hesitate to write.

**Comment by ERap320** [comment]
Looks like this issue was solved with the changes made for #17, so I'll close it for now.
I'll immediately merge these fixes to master.
