### ISSUE TITLE
Unsupported chars

### ISSUE THREAD

**Issue by zGitHubDev** [ERap320/LenovoWatchMOD#7]
If the sms, contact name or any other text has a non standard english charachter  e.g (á,é,ó,ő) the watch cat the rest of the text and show nothing, just empty spaces.

Solution 1: If the app send wrong messages to the watch it should fix it. 
Solution 2: if  this chars are not supported by the watch itself the app should change this to a standar esc char eg ? and send this text to the watch

**Comment by ERap320** [comment]
Hi @zGitHubDev, I suppose you are using the Watch X, because the Watch 9 doesn't have a screen.
I'm sorry but even if I could change the code of the app the way you describe I wouldn't be able to test the result since I only own a Watch 9.

Changing the behaviour of the app from the smali code is also a bit tricky. I'll try when I'll have a bit of spare time, but for now I can't promise you anything.
Moreover, I think a functional issue like this one will be addressed soon by the developers of the original app. If an update of the app is released and I haven't updated the mod for it in one or two days (this usually means I've not noticed the new version) feel free to contact me.

**Comment by zGitHubDev** [comment]
Hi @ERap320 ,

Thanks your quick answer. Yes you are right I have a Watch X Plus, which has a screen, I understand that difficult to test without a proper device. :(
I did a short look on the evening, i decomplied the app to java, found the proper palce and modified the code, I hope it will fix the bug.  Now I have to somehow recompile it and create an apk again and test it. Unfortunately I have not so much free time also but, I hope I can do it soon, I'll nofity you,
Why you are modifing smail and not java?
Connection with your suggestion to contact with the official developer, I did it using the app I have no answer about a month. Maybe I'll try the app email address, but I'm affraid they won't do it as official this watch is only produced to China, that's why the weather feature is not working,

**Comment by ERap320** [comment]
I have decompiled the app in smali because I used APK Easy Tool to perform the canges. It decompiles and recompiles everything without a problem. I explained it in #1.
It was just the first thing I found, and not being an experienced native Android developer I didn't know anything else.

What tool did you use to decompile it to Java? I'm very interested in something like that, it could benefit the mod in many ways.

**Comment by zGitHubDev** [comment]
Hi,

I found 2 tools the first one was an online you just have to upload the apk and got the result on the web. 
http://www.javadecompilers.com/apk but there were too much file to compy one-by-one, so I searched another. This one is a desktop tool called jadx , and download from here https://bintray.com/skylot/jadx/releases/v0.8.0#files

**Comment by zGitHubDev** [comment]
Hi,

I created a fix for this issue and also would like to share my experiences.
1. Decompling to Java code is good way to understand the code and help fixing the bug, but unfortunatelly it is not working so easy as I expected. The problem is this app is too big, and during the decomplimation some code won't be the same as the origin or I found some code was not correctly decomplied just was an that error as a comment in the java file.
I spent plenty of time to make my decompiled project to buildable, in Android Studio but there were no success. :(
The working way is the following.
1. Use the jadx-gui tool to convert your apk to a java gradle project
2. Open this project in andorid studio
3. Create a new empty project in android studio and copy the files from the original to here you'd like to modify
4. Fix the build errors you can make this files more simple if you remove the unused, unnecessary codes.
5, Modify you want.
6. Install java2smali plugin to the studio
7. Create smali file from the modified projects.
8. Create smali files from the original files using the apktool (d)
9. Mix your smali files with the original
10. Recompile it using the apktool
11. Using the zipalign tool to optimize your app (required). Part of the andorid SDK
12. Sign your aligned app with apksigner  (required), also part of android SDK.

So I did a fix my opinion is upload the apk and modified smali to the repo,  if it's ok please create a new branch (WatchX) or give me right to create a new branch.

I'm plannig to fix more issue.

**Comment by ERap320** [comment]
Sorry for the wait, I've been through a very busy week.
I've added you as a collaborator to the repository, I think you'll be able to create a new branch and ask for a merge request that way.
